#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-psutil
Version  : 5.9.1
Release  : 99
URL      : https://files.pythonhosted.org/packages/d6/de/0999ea2562b96d7165812606b18f7169307b60cd378bc29cf3673322c7e9/psutil-5.9.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/d6/de/0999ea2562b96d7165812606b18f7169307b60cd378bc29cf3673322c7e9/psutil-5.9.1.tar.gz
Summary  : Cross-platform lib for process and system monitoring in Python.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-psutil-filemap = %{version}-%{release}
Requires: pypi-psutil-lib = %{version}-%{release}
Requires: pypi-psutil-license = %{version}-%{release}
Requires: pypi-psutil-python = %{version}-%{release}
Requires: pypi-psutil-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : procps-ng
BuildRequires : python3-dev

%description
This directory contains scripts which are meant to be used internally
(benchmarks, CI automation, etc.).

%package filemap
Summary: filemap components for the pypi-psutil package.
Group: Default

%description filemap
filemap components for the pypi-psutil package.


%package lib
Summary: lib components for the pypi-psutil package.
Group: Libraries
Requires: pypi-psutil-license = %{version}-%{release}
Requires: pypi-psutil-filemap = %{version}-%{release}

%description lib
lib components for the pypi-psutil package.


%package license
Summary: license components for the pypi-psutil package.
Group: Default

%description license
license components for the pypi-psutil package.


%package python
Summary: python components for the pypi-psutil package.
Group: Default
Requires: pypi-psutil-python3 = %{version}-%{release}

%description python
python components for the pypi-psutil package.


%package python3
Summary: python3 components for the pypi-psutil package.
Group: Default
Requires: pypi-psutil-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(psutil)

%description python3
python3 components for the pypi-psutil package.


%prep
%setup -q -n psutil-5.9.1
cd %{_builddir}/psutil-5.9.1
pushd ..
cp -a psutil-5.9.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656395861
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-psutil
cp %{_builddir}/psutil-5.9.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-psutil/51ede753f5d20b28226ab01c133ad67797eaf716
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-psutil

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-psutil/51ede753f5d20b28226ab01c133ad67797eaf716

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
